module.exports = {
    branchPrefix: 'renovate-github-sh/',
    dryRun: null,
    dependencyDashboardTitle: 'Renovate Dashboard -- Self-Hosted',
    extends: ['local>WolfSoko/nx-renovate-self-hosted:renovate-self-hosted.config.json5'],
    gitAuthor: 'Renovate Bot GitHub <bot@renovateapp.com>',
    platform: 'github',
    repositories: ['WolfSoko/nx-renovate-self-hosted', 'WolfSoko/wol-sok-mono', 'WolfSoko/nx-clean'],
    includeForks: false,
    dependencyDashboard: true,
    onboarding: false,
    autodiscover: false,
    allowCustomCrateRegistries: true,
    allowScripts: true,
    exposeAllEnv: true,
    allowPostUpgradeCommandTemplating: true,
    allowedPostUpgradeCommands: [
        '^\\[ -x \\.\\/\\.github\\/scripts\\/install-ubuntu-packages\\.sh ] && \\.\\/\\.github\\/scripts\\/install-ubuntu-packages\\.sh$',
        '^npm ci --ignore-scripts$',
        '^npm run prepare --if-present$',
        '^npm run format --if-present$',
        '^npx --no-install ng update (@[a-z0-9-~][a-z0-9-._~]*\\/)?[a-z0-9-~][a-z0-9-._~]* --from=\\d+\\.\\d+\\.\\d+ --to=\\d+\\.\\d+\\.\\d+ --migrate-only --allow-dirty --force$',
        '^npx --no-install ng lint --fix$',
        '^npx --no-install nx migrate (@[a-z0-9-~][a-z0-9-._~]*\\/)?[a-z0-9-~][a-z0-9-._~]* --from=(@[a-z0-9-~][a-z0-9-._~]*\\/)?[a-z0-9-~][a-z0-9-._~]*@\\d+\\.\\d+\\.\\d+ --to=(@[a-z0-9-~][a-z0-9-._~]*\\/)?[a-z0-9-~][a-z0-9-._~]*@\\d+\\.\\d+\\.\\d+$ || true$',
        '^npx --no-install nx migrate --run-migrations=migrations\\.json || true$',
        '^rm -f migrations.json || true$',
        '^npx --no-install nx workspace-lint$',
        '^npx --no-install nx affected --target=(lint|test) --all --parallel (--fix)?$',
        '^npx --no-install nx format:(check|write)$',
    ],
}
